version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 21
    groups:
      maven-minor-patch:
        update-types:
          - "minor"
          - "patch"
      maven-major:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    cooldown:
      default-days: 21
    groups:
      github-actions:
        patterns:
          - "*"
